foldername: YELP-NCF-b256-f8

# MLP
layers: [32, 16, 8]

# GMF
num_factors: 8

# Data
processed_data_root: data/processed/YELP/NCF/yelp5/
num_users: 215366
num_items: 95895


# Training
epochs: 100
batch_size: 256
lr: 0.001
optimizer: adam
dropout: 0
num_negative_instances_train: 4

# Evaluation
topK: 10
evaluation_threads: 1
verbose: 1
num_negative_instances_test: 99

# Loss
loss: BCE
