# Name 
foldername: frappe-dummy-v3

# Encoder
layers: [21, 16, 9]

# Data
processed_data_root: data/processed/FRAPPE/AE/frappe5Context/

# Training
epochs: 200
batch_size: 256
lr: 0.001
optimizer: adam
dropout: 0
noise: False
init_weights: True


# Evaluation
verbose: 1

# Loss
loss: MSE
