# Name 
foldername: frappeV2-

# Encoder
layers: [12, 9]

# Data
processed_data_root: data/processed/FRAPPE/CNCF/frapppe5ContextV2/

# Training
epochs: 100
batch_size: 256
lr: 0.001
optimizer: adam
dropout: 0
noise: False
init_weights: True


# Evaluation
verbose: 1

# Loss
loss: MSE
