# Name 
foldername: yelpV2-tanh-c13-b256

# Encoder
layers: [13, 6]

# Data
# processed_data_root: data/processed/YELP/CNCF/yelp5Context/
processed_data_root: data/processed/YELP/CNCF/yelp5ContextV2/

# Training
epochs: 100
batch_size: 256
lr: 0.001
optimizer: adam
dropout: 0
noise: False
init_weights: True


# Evaluation
verbose: 1

# Loss
loss: MSE
