foldername: frappe5V2-compiled

# MLP: in 32+32+12 = 76
layers: [76, 32, 16, 8]

# GMF
num_factors: 8

# Data
# processed_data_root: /work3/s212784/data/processed/YELP/yelp_2_ctx/
processed_data_root: data/processed/FRAPPE/CNCF/frapppe5ContextV2/
num_users: 654
num_items: 1127
num_context: 12

num_negative_instances_train: 4
num_negative_instances_test: 99

# Training
epochs: 100
batch_size: 256
lr: 0.001
optimizer: adam
dropout: 0

# Evaluation
topK: 10
evaluation_threads: 1
verbose: 1

# Loss
loss: BCE
